version: '3'

services:
# MS SQL SERVER **************************************************
  mssql_dev:
    container_name: mssql_dev
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Pass@word11
      - ACCEPT_EULA=Y
    ports:
      - "15785:1433"
    volumes:
      # - sqlsystem_dev:/var/opt/mssql/:cached
      - ./sqlsystem_dev:/var/opt/mssql/
# POSTGRES **************************************************************
  postgres_dev:
    container_name: postgres_dev
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pass@word11
    ports:
      - "14785:5432"
    volumes:
      # - pgdata_dev:/var/lib/postgresql/data:cached
      - ./pgdata_dev:/var/lib/postgresql/data

volumes:
  mssqldata_dev:
  pgdata_dev: