# file: webservers.yml
---
- hosts: win
  gather_facts: yes
  tasks:
    - name: Install Chocolatey on Windows
      win_chocolatey: 
        name: procexp 
        state: present
    - name: Ensure 7-Zip is installed via Chocolatey
      win_chocolatey:
        name: 7zip
        state: present      